<?php
// echo "<pre>";
// print_r($productlist);



?>
<style>
   table {
      width: 700px;
      text-align: center;
      border: 1px solid #fff;
      border-spacing: 1px;
      font-family: 'Cairo', sans-serif;
      margin: auto;
   }

   caption {
      font-weight: bold;
   }

   table td {
      padding: 10px;
      background-color: #eee;
   }

   table th {
      background-color: #333;
      color: #fff;
      padding: 10px;
   }

   img {
      width: 90px;
      height: 90px;
   }

   .view,
   .delete {
      border: none;
      padding: 5px 10px;
      color: #fff;
      font-weight: bold;
   }

   .view {
      background-color: #03A9F4;
   }

   .delete {
      background-color: #E91E63;
   }

   .tablefoot {
      padding: 0;
      border-bottom: 3px solid #009688;
   }
   .overlay {
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  background: rgba(0, 0, 0, 0.7);
  transition: opacity 500ms;
  visibility: hidden;
  opacity: 0;
}
.overlay:target {
  visibility: visible;
  opacity: 1;
}

.popup {
  margin: 70px auto;
  padding: 20px;
  background: #fff;
  border-radius: 5px;
  width: 30%;
  position: relative;
  transition: all 5s ease-in-out;
}

.popup h2 {
  margin-top: 0;
  color: #333;
  font-family: Tahoma, Arial, sans-serif;
}
.popup .close {
  position: absolute;
  top: 20px;
  right: 30px;
  transition: all 200ms;
  font-size: 30px;
  font-weight: bold;
  text-decoration: none;
  color: #333;Attribute value 0 = 44F;
}
.popup .content {
  max-height: 100%;
  overflow: auto;
}

@media screen and (max-width: 700px){
  .box{
    width: 70%;
  }
  .popup{
    width: 70%;
  }
}
</style>
<body>
<h2 style="margin-left: 40%;">Product Lists</h2>
<table id="myTable">
   <caption><a href="/product/view">Home</a></caption>
   <caption><a href="/order/view">Order</a></caption>
 

   <thead>
      <tr>
         <th>Photo</th>
         <th>Product Name</th>

         <th>Price</th>
         <th>Category</th>
         <th>Quantity</th>
         <th>Action</th>
      </tr>
   </thead>
   <tbody>
 
      <?php 
      
        if(isset($productlist)) {
           foreach ($productlist as $key) { ?>
            <form action="/product/orderPlaced" method="post">
         <tr>
            <td><img src="https://cdn2.vectorstock.com/i/1000x1000/95/51/little-boy-logo-vector-28159551.jpg" alt="img"></td>

            <td><input type="hidden" name="name" value="<?php echo $key['name']; ?>"><?php echo $key['name']; ?></td>

            <td><input type="hidden" name="price" value="<?php echo $key['price']; ?>"><?php echo $key['price']; ?></td>

            <td><input type="hidden" name="category" value="<?php echo $key['category']; ?>"><?php echo $key['category']; ?></td>

            <td><input type="hidden" name="quantity" value="<?php echo $key['quantity']; ?>"><?php echo $key['quantity']; ?></td>

            <td><input type="hidden" name="id" value="<?php echo $key['_id']['$oid'] ?>">
              <input type="submit" name="submit" value="Add" ></td>
            </tr>
         </form>
      <?php } } ?>
   </tbody>
   <tfoot>
      <td colspan="5" class="tablefoot"></td>
   </tfoot>
</table>
</body>